# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

leftstring A0 = "Source"
leftstring B0 = "Destination"
leftstring C0 = "Weight"
let A1 = 1
let B1 = 2
let C1 = 0.5
let A2 = 2
let B2 = 3
let C2 = 0.6
let A3 = 3
let B3 = 1
let C3 = 0.9
goto C3 A0
