# This data file was generated by the Spreadsheet Calculator.
# You almost certainly shouldn't edit it.

set autowrap numeric craction = 1
leftstring A0 = "source"
leftstring B0 = "target"
leftstring C0 = "weight"
let A1 = 234
let B1 = 23
let C1 = 1
goto C2 A0
