name: Upload Python Package

on:
  release:
    types: [published] # Only trigger when a GitHub Release is published

permissions:
  contents: read # Allow reading repository contents
  # id-token: write # NOT needed if you're not using trusted_publisher

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: # Recommended for production deployments (still good practice)
      name: pypi
      url: https://pypi.org/p/workforce # Link to your PyPI project page (optional)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Update to v4 for the latest version

      - name: Set up Python
        uses: actions/setup-python@v5 # Update to v5 for the latest version
        with:
          python-version: '3.x' # Or a specific version like '3.12'
          # cache: 'pip' # Uncomment to enable pip caching for faster installs

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel # Ensure setuptools and wheel are installed explicitly

      - name: Build package
        run: python -m build --sdist --wheel # Explicitly build sdist and wheel

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 # Use the recommended stable tag
        with:
          user: __token__ # This tells Twine to use an API token
          password: ${{ secrets.PYPI_API_TOKEN }} # This retrieves the token from your GitHub Secrets
          # trusted_publisher: true # Remove or comment out this line